# main menu navigation
menu:
  Posts: /
  Sitemap: /sitemap/
  #  Archives: /archives/
  # Hexo: /categories/Hexo/
  # LeetCode: /categories/LeetCode/
  # PWN: /categories/PWN/
  # Operation System: /categories/Operation-System/
  Github: https://github.com/BenedictNgHK
  Email: mailto:yuzewuchina@outlook.com
  Friend Links: /friendlinks/
# Images
favicon: /images/icon.png
## Post default banner image
## Please specify width and height for google's structured data (Schema.org SEO)
default:
  url: /images/default.jpg
  width: 1280
  height: 720

# Font
## availableFontList: [
##   'noto-sans-kr',
##   'spoqa-han-sans-kr',
##   'spoqa-han-sans-jp'
## ]
## If you don't want font, you shouldn't specify the font.
font:

# Enable Latex
latex: true
# Dynamic menu with scrolling
dynamic_menu: true

# Highlight theme
## You can also use various themes in `css/highlights`
highlight: rainbow

# Related posts
## If you don't want `related posts` feature, you should specify the value as 0.
## If you want more related posts, you can do it too.
## But I don't recommend to specify over than 3.
related_posts: 3 # default enabled as 3

# Profile
profile:
  image: /images/avatar.jpg
  gravatar:
  link:
  description: "Social Media"
  social:
    github: https://github.com/BenedictNgHK
    facebook: https://www.facebook.com/BenedictNgYuzeWu # Facebook property also used in `article:author` meta tag.
    linkedin: https://www.linkedin.com/in/yuze-wu-a100011ba
    #    email: mailto:yuzewuchina@gmail.com
    instagram:
    twitter:
#    rss: /atom.xml
# Footer widgets
## Don't use over than 3 widgets.
## availableWidgetList: [
##   'archives',
##   'categories',
##   'recent-posts',
##   'tag-cloud',
##   'tags'
## ]
## If you don't want widget, you shouldn't specify widgets.
widgets:
  - recent-posts
  #  - archives
  - categories
# Latex
mathjax:
  tags: none # or 'ams' or 'all'
  single_dollars: true # enable single dollar signs as in-line math delimiters
  cjk_width: 0.9 # relative CJK char width
  normal_width: 0.6 # relative normal (monospace) width
  append_css: true # add CSS to pages rendered by MathJax
  every_page: false # if true, every page will be rendered by MathJax regardless the `mathjax` setting in Front-matter
  packages: amsmath # extra packages to load
  extension_options: {}

# Other Services
google_analytics: G-3WGY09S1RR
google_site_verification:
naver_site_verification:

# Open graph
facebook:
fb_admin:
twitter:
google_plus:
#liveRe
# liveRe:
#  uid:
